### ISSUE TITLE
Access server object from server methods

### ISSUE THREAD

**Issue by cjnqt** [devinivy/haute-couture#14]
Is there a way to access the `server` object from within server methods?

I guess it should be possible to  `bind` the server object (by setting `options: {bind: server}`, see [here](http://hapijs.com/tutorials/server-methods#bind)) but I haven't been able to do this with haute couture

**Comment by devinivy** [comment]
Yes!

With haute-couture any time you would write this,
```js
// methods.js
module.exports = [{
    name: 'someName',
    method: (x, y, next) => {/* ... */}
}];
```

you could also write the same thing this way to access the `server` and plugin registration `options`,
```js
// methods.js
module.exports = (server, options) => {

    return [{
        name: 'someName',
        method: (x, y, next) => {/* ... */}
    }];
};
```
