### ISSUE TITLE
Setting a global route prefix?

### ISSUE THREAD

**Issue by cjnqt** [devinivy/haute-couture#28]
Can't find a way to set the `prefix` option (this one: https://hapijs.com/tutorials/plugins#plugin-options). It should be supplied when registrering the plugin.

Is that possible when using haute-couture?

**Comment by devinivy** [comment]
Yes!  You will want to export an object like,
```
module.exports = {
    plugins: { register: MyPlugin, options: { my, plugin, options } },
    options: { routes: { prefix: '/api' } }
};
```

It can get confusing since you can include both options for your plugin (whatever they may be) and registration options for hapi (like `prefix`).

**Comment by cjnqt** [comment]
Hmmm... so how do you use this to set a `prefix` on every route? (I seem to be slow today 🙃)

**Comment by devinivy** [comment]
No worries!  Okay, I see what you're saying.  haute-couture will output a plugin registration function.  Route prefixes are set during a plugin's registration, not within the plugin itself.  So typically you would set this option when you register your haute-couture-made plugin to the hapi server (e.g. using glue).

However, you could also set the prefix _within_ a plugin by wrapping it, if you like!

```js
// index.js
const HauteCouture = require('haute-couture');

module.exports = (server, options, next) => {

  const wrapped = HauteCouture.using();
  wrapped.attributes = { name: 'my-hapi-plugin-wrapped' };

  return server.register({ register: wrapped, options }, { routes: { prefix: '/api' } }, next);
};

module.exports.attributes = {
  name: 'my-hapi-plugin'
};
```

**Comment by cjnqt** [comment]
Great - I put it in the Glue manifest ```
            plugin: '../lib',
            options: {
                routes: {
                    prefix: '/api/v1'
                }
            }
```
Thanks for the help!

**Comment by devinivy** [comment]
👍 welcome!  Glad you got it working.
