### ISSUE TITLE
bind server object to a method

### ISSUE THREAD

**Issue by tinchoz49** [devinivy/haute-couture#37]
Hi @devinivy, how are you?

I've been testing haute-coutere in a project and I really like the idea. 

One thing that I couldn't understand is how can I bind the `server` object to a `method` function. What is the best way to define this kind of options?

btw, thanks for your amazing work on the hapi ecosystem.

**Comment by devinivy** [comment]
Hi @tinchoz49—thanks for the thanks!

If you want access to the `server` inside a server method, haute-couture actually does have a feature that should help you.  Any haute-couture file may export a function that takes the `server` and `options` as arguments and returns a configuration.  For a server method you might turn this,
```js
// before
module.exports = {
    name: 'example',
    method: (x) => x
};
```

into this,
```js
// after
module.exports = (server) => ({
    name: 'example',
    method: (x) => x + server.app.y
});
```

And again, this works with any haute-couture item, not just server methods.  Let me know if that helps!

**Comment by tinchoz49** [comment]
yes!! that's what exactly I need! thanks for the quick answer!
